### ISSUE TITLE
Backup filename

### ISSUE THREAD

**Issue by haietza** [Syxton/moodle-tool_coursearchiver#37]
The filename for the backup created is left as backup.mbz, so when the job tries to find it to move it (it looks for a file named backup-moodle2-course-id...) it errors saying the archive cannot be created.

I think this can be fixed by changing the mode to MODE_GENERAL (from MODE_AUTOMATED) in classes/processor.php:628.

**Comment by nomisge** [comment]
Same Issue here.
Backups are impossible for me. 

`copy([some_path].../CourseArchives/2023/2023-09-01-ID-1965-IDNUM-DKZ.FR.NW.202223.CH/9c-2022-23-Ch-9c.mbz):` Failed to open stream: No such file or directory in [path_to_moodle]/lib/filestorage/file_system_filedir.php on line 234`

**Comment by Syxton** [comment]
Fixed! YAY!

**Comment by haietza** [comment]
@Syxton The change for #49 did not fix this issue. Still getting this error: 
Warning: copy(/var/www/moodledata/filedir/8c/96/8c96a486d5801e0f4ab8c411f561f1c687e1f865): failed to open stream: No such file or directory in /var/www/html/lib/filestorage/file_system_filedir.php on line 234

Please reopen and see suggested fix above.

**Comment by Syxton** [comment]
@haietza I'd love to better understand this error.  So far I have been unable to duplicate the issue on my end.   What is the full and short name and idnumber of the course that is failing?  Also what are your settings for auto backup?

![image](https://github.com/Syxton/moodle-tool_coursearchiver/assets/989354/5c9df89b-f19e-498f-94f7-1486f17a52ec)

**Comment by haietza** [comment]
@Syxton The full name and short name are both dev_meltonml2. The course ID is 3 (there is no idnumber set). We are using the attached auto backup settings (the backups dir is writable by apache).

As I mentioned in my initial post, changing the backup mode seems to resolve the error.

Thanks for looking into this!

![Screenshot 2023-10-03 at 1 52 45 PM](https://github.com/Syxton/moodle-tool_coursearchiver/assets/669666/2d6e0699-3547-4c47-b7a0-9b9aae34088e)

**Comment by Syxton** [comment]
@haietza Should be fixed in the new release v4.1.8.  Thank you for your help and patience.

**Comment by haietza** [comment]
@Syxton Thank you for your work on the project!
